language: python
arch:
  - amd64
  - arm64
os: linux
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install -U setuptools
  - python setup.py install
# command to run tests
script: python setup.py test
